services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  keycloak:
    image: 's292567/keycloak'
    container_name: keycloak
    ports:
      - "8080:8080"
    #    environment:
    #      - KEYCLOAK_ADMIN_PASSWORD=admin
    #      - KEYCLOAK_ADMIN=admin
    command: start-dev
